---
deployment:
  tasks:
    - rsync -a --delete --exclude='.git' . /home/simpxlow/wrenfieldhouse.com/
    - printf "DirectoryIndex index.html\n" > /home/simpxlow/wrenfieldhouse.com/.htaccess
    - chmod 644 /home/simpxlow/wrenfieldhouse.com/.htaccess
