---
deployment:
  tasks:
    - rsync -a --delete --exclude='.git' . /home/simpxlow/wrenfieldhouse.com/
    - find /home/simpxlow/wrenfieldhouse.com -type f -exec chmod 644 {} \;
    - find /home/simpxlow/wrenfieldhouse.com -type d -exec chmod 755 {} \;
    - printf "DirectoryIndex index.html\n" > /home/simpxlow/wrenfieldhouse.com/.htaccess
    - chmod 644 /home/simpxlow/wrenfieldhouse.com/.htaccess
